### ISSUE TITLE
Use from a PHP command-line script?

### ISSUE THREAD

**Issue by donnekgit** [peterolson/pinyinify#2]
Can you give a bit more info on how to use this from PHP?  I've run mpm install, and it gives a separate node-modules dir, with a pinyinify dir below that, and another node-modules dir inside that, with nodejieba and pinyin dirs. Thanks.

**Comment by peterolson** [comment]
I'm not aware of any way that npm modules can be used from PHP. It might be possible, but I'm not exactly sure how this could be done.

**Comment by donnekgit** [comment]
Hi Peter

Sorry - I didn't express myself very well, mainly because I've never used Node.js before.  I just meant how to run it from the command-line (the output of which I can then ingest into PHP) - it wasn't working for me.  I was using v4 of Node.js, and once i upgraded to v6, it works.  So now i have a slightly different question (or enhancement request?):

I have the following as tryme.sh:
```
#! /usr/bin/env node
var pinyinify = require("pinyinify");
console.log(pinyinify("自们都是党员，人人可以随便发表意见。"));
```
and if I run tryme.sh, I get the expected:
`zì men dōu shì dǎngyuán, rénrén kěyǐ suíbiàn fābiǎoyìjiàn.`

However, i'd also like the hanzi reflected back using the same wordbreaks.  I can get this if I add to tryme.sh:
```
var nodejieba = require("nodejieba");
var result = nodejieba.cut("自们都是党员，人人可以随便发表意见。");
console.log(result);
```
which gives:
`[ '自', '们', '都', '是', '党员', '，', '人人', '可以', '随便', '发表意见', '。' ]`

Is there any way to get the two outputs (hanzi and pinyin, both word-separated) using the one call to pinyinify?

Thanks.

**Comment by peterolson** [comment]
No, pinyinify doesn't currently have this functionality. Calling pinyinify on each element of the result from `nodejieba.cut` might do what you want:

```
var nodejieba = require("nodejieba"),
    pinyinify = require("./pinyinify");
var segments = nodejieba.cut("自们都是党员，人人可以随便发表意见。");
var pinyinWords = segments.map(pinyinify);
console.log(segments, pinyinWords);
```

**Comment by donnekgit** [comment]
Hi Peter
That doesn't quite work for me (I get newlines in the pinyinwords section), but I can certainly experiment.  Thanks for all your help.
