### ISSUE TITLE
comparison to other libraries?

### ISSUE THREAD

**Issue by dcsan** [peterolson/pinyinify#3]
I am wondering how your lib compares to other pinyin converters?

right now I am using

https://www.npmjs.com/package/pinyin

but it gives many problems:

![image](https://user-images.githubusercontent.com/514002/39803024-46dd8e04-53a2-11e8-9309-f8e86d82229c.png)

![image](https://user-images.githubusercontent.com/514002/39803036-4d06b468-53a2-11e8-9b58-0b3e7d1b73fa.png)

now I have to do this:

```js
const SPECIAL_CASE_PINYIN = {
  "了": "le",
  "除了": "chúle",
  "还是": "háishi",
  "还有": "háiyou",
  "还": "hái",
  "都":"dōu",
  "什么": "shénme",
  "怎么": "zěnme",
  "那么": "nàme",
  "为什么": "wéishěnme",
  "怎么样": "zěnmeyang",
  "太好了": "tàihǎole"
}
```

do you have a different technique than the other NPM packages?

**Comment by peterolson** [comment]
pinyinify outputs this for your example:

    tàihǎole. wǒmen yīqǐ qù. hǎo ma? shàngwǔ shídiǎn zěnmeyàng?

This seems to be correct. It seems like the other library you are using tries to get the pinyin from individual characters, instead of first doing word segmentation and then getting the most common tone from a dictionary of words.

Does that answer your question?

**Comment by peterolson** [comment]
Hi, this isn't recursion. Notice that it calls the [`pinyin` function](https://www.npmjs.com/package/pinyin), which is part of a different library, not the `pinyinify` function.

What is does is that if the word is not found in the dictionary, then it calls `pinyin` on each character of the word. Each character might have more than one reading, so it just takes the first one returned by `pinyin`.

The `pinyinDict` file just has the most likely pronunciation for each word.

**Comment by dcsan** [comment]
oh, the pinyin lib is the one that I'm using that gives awful results.
so you have your own sorted "most likely" pinyinDict, maybe for disambiguation, and then using `pinyin` module for a fallback?

did you create the pinyinDict ?

I also think node-jieba had a frequency table within it, but i haven't dug into that so far...

**Comment by peterolson** [comment]
Yes that is correct.

**Comment by peterolson** [comment]
They have a character-pinyin dictionary, not a word-pinyin dictionary. Getting the pinyin of whole words is more accurate than getting the pinyin of individual characters.

**Comment by dcsan** [comment]
ah ok I get it. thanks very much!

how did you build that dictionary? is it based on any corpus of translated pinyin materials?
this seems like a huge step up from pinyin.js

**Comment by peterolson** [comment]
It's adapted from the cc-cedict
